# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     pages-themes/slate@v0.2.0

# Setup
title:            Michael's Blog
description: 　　　欢迎你来到我的个人博客

author:
  name:           'Michael'
  url:             https://jumpmanmichael.github.io/

plugins:
- jekyll-remote-theme 
