# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     pages-themes/slate@v0.2.0

# Setup
title:            Michael's Blog
tagline:          'A Jekyll theme'

author:
  name:           'Michael'
  url:             https://jumpmanmichael.github.io/

plugins:
- jekyll-remote-theme 
